App/user/models.py
# -- * -- coding : utf-8 -- * --
from flask import current_app
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

from App.extension import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash



class User(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255),unique=True,nullable=False)
    password_hash = db.Column(db.String(255),nullable=False)
    email = db.Column(db.String(255),unique=True,nullable=False)
    create_time = db.Column(db.DATETIME,nullable=False,default=datetime.now)
    activation = db.Column(db.Boolean,default=False)
    gender = db.Column(db.String(10),default='秘密')
    signature = db.Column(db.Text,default='飒飒大苏打')
    avatar = db.Column(db.String(300),default='')

    # 保护字段
    @property
    def password(self):
        raise AttributeError('密码是不可读属性')

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash( self.password_hash, password)

    # 生产token
    def generate_token(self):
        s = Serializer(current_app.config['SECRET_KEY'],expires_in=current_app.config['EXPIRES_IN_TOKEN'])
        return s.dumps({'id': self.id})

    # 校验
    @staticmethod
    def check_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False

        user = User.query.get(data.get('id'))
        if user is None:
            return False
        if not user.activation:
            user.activation = True
            db.session.add(user)
        return True

App/user/forms.py
# -- * -- coding : utf-8 -- * --
from  wtforms.validators import EqualTo,Email,DataRequired,Length
from flask_wtf import FlaskForm
from wtforms import PasswordField,SubmitField,StringField

class RegisterFrom(FlaskForm):
    username = StringField('用户名',validators=[DataRequired(),Length(2,28,message=["用户名必须在2-28之内"])])
    password = PasswordField('密码', validators=[DataRequired(), Length(6, 66, message=["密码必须在6-66之内"])])
    password_equalto = PasswordField('确认密码', validators=[DataRequired(), EqualTo('password',message=["密码不一致"])])
    email = StringField('邮箱',validators=[DataRequired(),Email(message='邮箱格式有误')])
    submit = SubmitField('提交')

App/__init__.py
from flask import Flask

from App.config import envs
from App.extension import config_extension
from App.user.views import Blueprint

def create_app(config_name):
    #app 实例化
    app = Flask(__name__)

    app.config.from_object(envs.get(config_name))
    envs[config_name].init_app(app)
    # 实例化第三方
    config_extension(app)

    return app

App/user/__init__.py
# -- * -- coding : utf-8 -- * --
from .views import user

App/user/views.py
# -- * -- coding : utf-8 -- * --
from flask import Blueprint,render_template,redirect,url_for,request

from App.extension import db
from App.user.forms import RegisterFrom
from App.user.models import User
from utlis import restful
from utlis.email import send_email

user = Blueprint('user',__name__)

def get_error(form):
    message = form.error.popitem()[1][0]
    return message


@user.route('/register/',methods = ['POST','GET'])
def register():
    if request.method == 'POST':
        form = RegisterFrom(request.form)
        if form.validate():
            password = form.password1.data
            email = form.email.data
            e = User.query.filter(User.email == email).first()
            if e:
                return restful.RestfulResult('对不起,该用户已存在！')
            user = User(password=password,email=email)
            db.session.add(user)
            db.session.commit()
            return restful.success()
        else:
            return restful.params_error(message=get_error(form))
    return render_template('user/register.html')

@user.route('/activate/<token>',methods = ['POST','GET'])
def activate(token):
    if User.check_token(token):
        return redirect(url_for('user.login'))
    else:
        return redirect(url_for('user/register'))

@user.route('/login/',methods = ['POST','GET'])
def login():
    return '登录'

@user.route('/index/',methods = ['POST','GET'])
def index():
    return 'index'

App/templates/user/base.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html'as wtf %}

{% block title %}
    {% if not title %}
        comm
    {% endif %}
    {% endblock %}
{% block content %}
{% endblock %}

App/templates/user/email.html
<p>{{ username }},欢迎您注册</p>
<p>账户激活,请点击右边链接 {{ url_for('user.activate', token=token, _external=True) }} 激活</p>

App/templates/user/register.html
{% from "public/_macro.html" import static %}

<!doctype html>
<html lang="en">
<head>
    {#    <meta name="csrf-token" content="{{ csrf_token() }}">#}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>注册</title>
    <link rel="stylesheet" type="text/css" href="{{ static("user/css/index.css") }}">
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static("public/sweetalert/sweetalert.css") }}">
    <script src="{{ static("public/sweetalert/sweetalert.min.js") }}"></script>
    <script src="{{ static("public/sweetalert/zlalert.js") }}"></script>
</head>
<body>
<div class="main_contener">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        {#         <span id="return_to_span">{{ return_to }}</span>#}
        <div class="siup_in_title">
            {#             <a href="{{ url_for("front.index") }}"><img src="{{ static("front/images/blogin.png") }}" alt=""></a>#}
        </div>
        <div class="modal-content" style="border: none;">
            <div class="col-left"></div>
            <div class="col-right">
                <div class="modal-header">
                    <h4 class="modal-title" id="loginModalLabel" style="font-size: 18px;">注册</h4>
                </div>
                <div class="modal-body">
                    <section class="box-login v5-input-txt" id="box-login">
                        <ul>
                            <li class="form-group">邮箱：
                                <div class="input-group">
                                    <input type="text" class="form-control" name="email" placeholder="邮箱号码">
                                    <span class="input-group-btn">
                                            <button class="btn btn-default" id="send-capcha" style="padding: 10px 0px">发送验证码</button>
                                    </span>
                                </div>
                            </li>
                            <li class="form-group">邮箱验证码：<input class="form-control" name="email-captcha"
                                                                placeholder="请输入邮箱验证码" type="text"></li>


                            <li class="form-group">密码：<input class="form-control" name="password1"
                                                             placeholder="请输入密码" type="password"></li>
                            <li class="form-group">确认密码：<input class="form-control" name="password2"
                                                               placeholder="请输入确认密码" type="password"></li>
                        </ul>
                        <p class="good-tips marginB10">已有账号？<a
                                href="{{ url_for("user.login") }}">立即登陆</a></p>
                        <div class="login-box marginB10">
                            <button type="button" class="btn btn-micv5 btn-block globalLogin" id="signup-now">注册
                            </button>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-4">
    </div>
</div>


</body>
</html>